// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiBPaH8leU5MpjBmwwvFEYd9fPmum0OI0',
    appId: '1:655446092038:android:eb92943f5d64b9b49b1687',
    messagingSenderId: '406099696497',
    projectId: 'productstore-17f02',
    authDomain: 'productstore-17f02.firebaseapp.com',
    databaseURL:
        'https://productstore-17f02-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'productstore-17f02.appspot.com',
    measurementId: 'G-JN95N1JV2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiBPaH8leU5MpjBmwwvFEYd9fPmum0OI0',
    appId: '1:655446092038:android:eb92943f5d64b9b49b1687',
    messagingSenderId: '406099696497',
    projectId: 'productstore-17f02',
    databaseURL:
        'https://productstore-17f02-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'productstore-17f02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiBPaH8leU5MpjBmwwvFEYd9fPmum0OI0',
    appId: '1:655446092038:android:eb92943f5d64b9b49b1687',
    messagingSenderId: '406099696497',
    projectId: 'productstore-17f02',
    databaseURL:
        'https://productstore-17f02-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'productstore-17f02.appspot.com',
    androidClientId:
        '406099696497-17qn06u8a0dc717u8ul7s49ampk13lul.apps.googleusercontent.com',
    iosClientId:
        '406099696497-irb7edfevfkhi6t5s9kbuq1mt1og95rg.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebase.messaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiBPaH8leU5MpjBmwwvFEYd9fPmum0OI0',
    appId: '1:655446092038:android:eb92943f5d64b9b49b1687',
    messagingSenderId: '406099696497',
    projectId: 'productstore-17f02',
    databaseURL:
        'https://productstore-17f02-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'productstore-17f02.appspot.com',
    androidClientId:
        '406099696497-17qn06u8a0dc717u8ul7s49ampk13lul.apps.googleusercontent.com',
    iosClientId:
        '406099696497-irb7edfevfkhi6t5s9kbuq1mt1og95rg.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebase.messaging',
  );
}
